using System.IO.Compression;
using System.Text;
using ChunkPilot.App.Presentation;
using ChunkPilot.Core;
using ChunkPilot.Infrastructure;

namespace ChunkPilot.UnitTests;

public sealed class PropertiesAndSafetyTests : IDisposable
{
    private readonly string root = Path.Combine(Path.GetTempPath(), "ChunkPilot-safety-" + Guid.NewGuid().ToString("N"));
    private readonly AppDataPaths paths;
    private readonly SafeFileService files;

    public PropertiesAndSafetyTests()
    {
        Directory.CreateDirectory(root);
        paths = new AppDataPaths(Path.Combine(root, "appdata"));
        paths.EnsureCreated();
        files = new SafeFileService(paths);
    }

    [Fact]
    public void Server_properties_round_trip_preserves_comments_order_and_line_endings()
    {
        const string original = "# generated by user\r\nmotd=Original\r\ncustom-key = keep me\r\n\r\n";
        var document = ServerPropertiesDocument.Parse(original);
        document.Set("motd", "Updated");
        var result = document.ToString();
        Assert.Contains("# generated by user\r\n", result, StringComparison.Ordinal);
        Assert.Contains("custom-key = keep me\r\n", result, StringComparison.Ordinal);
        Assert.Contains("motd=Updated\r\n", result, StringComparison.Ordinal);
        Assert.EndsWith("\r\n", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Server_properties_round_trip_two_line_unicode_motd_without_double_escaping()
    {
        const string motd = "§bCopper Valley\n§fBuilders' café 世界";
        var document = ServerPropertiesDocument.Parse("motd=Old\r\n");

        document.Set("motd", motd);
        var written = document.ToString();

        Assert.Contains("motd=§bCopper Valley\\n§fBuilders' café 世界\r\n", written, StringComparison.Ordinal);
        Assert.DoesNotContain("\\\\n", written, StringComparison.Ordinal);
        Assert.Equal(motd, ServerPropertiesDocument.Parse(written).Values["motd"]);
    }

    [Fact]
    public void Server_properties_decode_existing_java_unicode_escape_for_lossless_motd_editing()
    {
        var document = ServerPropertiesDocument.Parse("motd=\\u00a7bHello\\nworld\n");

        Assert.Equal("§bHello\nworld", document.Values["motd"]);
    }

    [Fact]
    public void Motd_is_truthfully_marked_restart_required()
    {
        Assert.Contains("motd", ServerPropertyPresentation.RestartRequiredKeys);
    }

    [Fact]
    public async Task Atomic_text_write_preserves_bom_and_creates_configuration_recovery()
    {
        var server = Path.Combine(root, "server");
        Directory.CreateDirectory(server);
        var path = Path.Combine(server, "server.properties");
        await File.WriteAllTextAsync(path, "motd=before\r\n", new UTF8Encoding(true));
        var content = await files.ReadTextAsync(server, "server.properties");
        await files.WriteTextAtomicAsync(server, content with { Content = "motd=after\r\n" });
        var bytes = await File.ReadAllBytesAsync(path);
        Assert.True(bytes.AsSpan().StartsWith(Encoding.UTF8.GetPreamble()));
        Assert.Contains("motd=after", await File.ReadAllTextAsync(path), StringComparison.Ordinal);
        Assert.NotEmpty(Directory.EnumerateFiles(paths.Recovery, "server.properties", SearchOption.AllDirectories));
    }

    [Fact]
    public void Path_canonicalization_prevents_parent_escape()
    {
        var server = Path.Combine(root, "server");
        Directory.CreateDirectory(server);
        Assert.Throws<UnauthorizedAccessException>(() => files.ResolveWithinRoot(server, @"..\outside.txt", mustExist: false));
    }

    [Fact]
    public async Task Zip_extraction_rejects_zip_slip()
    {
        var server = Path.Combine(root, "server");
        Directory.CreateDirectory(server);
        var zipPath = Path.Combine(server, "bad.zip");
        using (var archive = ZipFile.Open(zipPath, ZipArchiveMode.Create))
        {
            var entry = archive.CreateEntry("../escape.txt");
            await using var writer = new StreamWriter(entry.Open());
            await writer.WriteAsync("bad");
        }
        await Assert.ThrowsAsync<InvalidDataException>(() => files.ExtractZipAsync(server, "bad.zip", "extract"));
        Assert.False(File.Exists(Path.Combine(server, "escape.txt")));
    }

    [Theory]
    [InlineData("logs/latest.log", "logs/**", true)]
    [InlineData("world/region/r.0.0.mca", "logs/**", false)]
    [InlineData("session.lock", "session.lock", true)]
    public void Backup_exclusion_globs_match_as_expected(string path, string pattern, bool expected) =>
        Assert.Equal(expected, BackupService.ShouldExclude(path, [pattern]));

    [Fact]
    public void Backup_destination_must_be_outside_source()
    {
        var server = Path.Combine(root, "server");
        Directory.CreateDirectory(server);
        Assert.Throws<InvalidOperationException>(() =>
            BackupService.ValidateDestination(server, Path.Combine(server, "backups")));
        BackupService.ValidateDestination(server, Path.Combine(root, "backups"));
    }

    public void Dispose()
    {
        if (Directory.Exists(root))
            Directory.Delete(root, recursive: true);
    }
}

