import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, History as CalendarClock, Clipboard, Download, FolderOpen, Play, Plus, RefreshCw, Server as ServerIcon, Square, X as Trash2 } from '../design-system/Icons';
import type { ServerSummary } from '../bridge/types';
import { Button, ConfirmDialog, EmptyState, Metric, PanelTitle, SearchInput, Sparkline, StatusBadge, TextInput } from '../design-system/Primitives';
import { useAppStore } from '../state/store';
import { lifecycleAction } from './lifecycle';
import { connectionChoice } from './connectivity/ConnectionSummary';
import styles from './Page.module.css';

const formatBytes = (value: number | null, precision = 1) => value == null ? 'Unavailable' : value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(precision)} GB` : `${(value / 1024 ** 2).toFixed(precision)} MB`;
const formatPercent = (value: number | null) => value == null ? 'Unavailable' : `${value.toFixed(0)}%`;
const playerText = (server: ServerSummary) => server.playersOnline == null ? 'Unavailable' : server.playersMaximum == null ? `${server.playersOnline} online` : `${server.playersOnline} / ${server.playersMaximum}`;
const stateTone = (state: ServerSummary['state']) => state === 'Running' ? 'success' : state === 'Starting' || state === 'Restarting' ? 'info' : state === 'Crashed' || state === 'Unresponsive' ? 'danger' : state === 'BackingUp' || state === 'Restoring' ? 'warning' : 'neutral';
const mainJoiningAddress = (server: ServerSummary) => server.publicReachability === 'confirmed' && server.publicAddress
  ? server.publicAddress : server.lanAddress ?? server.localAddress;

export function DashboardPage({ onServers, onOpenServer, onCreate }: { onServers: () => void; onOpenServer: (server: ServerSummary) => void; onCreate: () => void }) {
  const snapshot = useAppStore(state => state.snapshot)!;
  const command = useAppStore(state => state.command);
  const busy = useAppStore(state => state.busy);
  const servers = snapshot.servers;
  const attention = servers.filter(server => server.lastError || server.state === 'Crashed' || server.lastBackupAt == null);
  const running = servers.filter(server => server.state === 'Running').length;
  const open = (server: ServerSummary) => onOpenServer(server);
  const lifecycleBusy = busy.has('servers.start') || busy.has('servers.stop');
  const lifecycle = (server: ServerSummary) => { const action = lifecycleAction(server, lifecycleBusy); if (action.method) void command(action.method, { serverId: server.id }).catch(() => undefined); };
  if (servers.length === 0) return <div className={styles.pageWrap}>
    <header className={styles.pageHeader}><div><h1>Welcome to ChunkPilot</h1><p>Your local control room for Minecraft servers.</p></div></header>
    <div className={styles.onboardingGrid}>
      <section className={styles.onboardingLead}><div className={styles.onboardingMark}><ServerIcon size={25} /></div><span className={styles.eyebrow}>Start locally</span><h2>Bring your first server online.</h2><p>Create a managed Vanilla server or add a folder you already use. Your worlds stay on this PC, and internet sharing remains off until you choose it.</p><div className={styles.actions}><Button variant="primary" icon={<Plus size={15} />} onClick={onCreate}>Create server</Button><Button icon={<Download size={15} />} onClick={() => void command('servers.import')}>Add existing</Button></div></section>
      <aside className={styles.readiness}><PanelTitle title="Ready when you are" /><div><strong>Local by default</strong><span>No account, cloud service, or public exposure.</span></div><div><strong>Managed Java</strong><span>ChunkPilot selects the runtime your server needs.</span></div><div><strong>World-safe operations</strong><span>Backups and recovery remain authoritative.</span></div></aside>
    </div>
  </div>;
  const primary = servers[0];
  return <div className={styles.pageWrap}>
    <header className={styles.pageHeader}><div><h1>Dashboard</h1><p>{servers.length === 1 ? 'Your server, ready for the next task.' : `${servers.length} servers · ${running} running`}</p></div><div className={styles.actions}><Button icon={<Download size={15} />} onClick={() => void command('servers.import')}>Add existing</Button><Button variant="primary" icon={<Plus size={15} />} onClick={onCreate}>Create server</Button></div></header>
    <div className={styles.workbenchGrid}>
      <div className={styles.workbenchMain}>
        <section className={styles.serverRoster}>
          <PanelTitle title={servers.length === 1 ? 'Active server' : 'Your servers'} meta={`${running} running`} action={<Button variant="subtle" onClick={onServers}>Open library <ArrowRight size={14} /></Button>} />
          {servers.length === 1 ? <div className={styles.featureServer}><div className={styles.featureIdentity}><div className={styles.featureIcon}>{primary.iconUrl ? <img src={primary.iconUrl} alt="" aria-hidden="true" /> : <ServerIcon size={25} />}</div><div><span className={styles.eyebrow}>{primary.ecosystem} · Minecraft {primary.minecraftVersion}</span><h2>{primary.name}</h2><p>{mainJoiningAddress(primary)}</p></div><StatusBadge tone={stateTone(primary.state)}>{primary.state}</StatusBadge></div><div className={styles.featureFacts}><div><span>Players</span><strong>{playerText(primary)}</strong></div><div><span>Memory</span><strong>{formatBytes(primary.memoryBytes)}</strong></div><div><span>Last backup</span><strong>{primary.lastBackupAt ? new Date(primary.lastBackupAt).toLocaleDateString() : 'Not recorded'}</strong></div></div><div className={styles.featureActions}><Button variant="subtle" onClick={() => open(primary)}>Manage server</Button>{(() => { const action = lifecycleAction(primary, lifecycleBusy); return <Button disabled={action.pending} variant={primary.state === 'Running' ? 'secondary' : 'primary'} icon={primary.state === 'Running' ? <Square size={12} /> : <Play size={13} />} onClick={() => lifecycle(primary)}>{action.label}</Button>; })()}</div></div> : <div className={styles.list}>{servers.slice(0, 6).map(server => { const action = lifecycleAction(server, lifecycleBusy); return <div className={styles.serverRosterRow} key={server.id}><div className={styles.identity}><div className={styles.serverIcon}>{server.iconUrl ? <img src={server.iconUrl} alt="" aria-hidden="true" /> : <ServerIcon size={17} />}</div><div className={styles.identityText}><strong>{server.name}</strong><small>{server.ecosystem} · {server.minecraftVersion}</small></div></div><StatusBadge tone={stateTone(server.state)}>{server.state}</StatusBadge><span className={styles.secondary}>{playerText(server)}</span><span className={styles.secondary}>{formatBytes(server.memoryBytes)}</span><Button variant="subtle" onClick={() => open(server)}>Manage</Button><Button disabled={action.pending} variant={server.state === 'Running' ? 'secondary' : 'primary'} icon={server.state === 'Running' ? <Square size={12} /> : <Play size={13} />} onClick={() => lifecycle(server)}>{action.label.replace(' server', '')}</Button></div>; })}</div>}
        </section>
        <section className={styles.activityLedger}><PanelTitle title="Recent activity" action={<Activity size={15} aria-hidden="true" />} />{snapshot.activity.length ? <div className={styles.list}>{snapshot.activity.slice(0, 5).map(item => <div className={`${styles.row} ${styles.activityRow}`} key={item.id}><div className={styles.identityText}><strong>{item.action}</strong><small>{new Date(item.timestamp).toLocaleString()}</small></div><span>{item.serverName || 'ChunkPilot'}</span><span>{item.result}</span><span className={styles.muted}>{(item.durationMs / 1000).toFixed(1)} s</span></div>)}</div> : <EmptyState title="No recent activity" detail="Confirmed lifecycle, backup, and management operations will appear here." />}</section>
      </div>
      <aside className={styles.workbenchRail}>
        {attention.length > 0 && <section className={styles.railSection}><PanelTitle title="Needs attention" meta={`${attention.length}`} />{attention.slice(0, 3).map(server => <button className={styles.attentionLink} key={server.id} onClick={() => open(server)}><i /><span><strong>{server.name}</strong><small>{server.lastError ?? 'No verified backup recorded'}</small></span><ArrowRight size={14} /></button>)}</section>}
        <section className={styles.railSection}><PanelTitle title="Host performance" /><div className={styles.hostMetrics}><div><span>CPU</span><strong>{formatPercent(snapshot.host.cpuPercent)}</strong></div><div><span>Memory</span><strong>{formatBytes(snapshot.host.usedMemoryBytes)}</strong><small>{snapshot.host.totalMemoryBytes == null ? 'Total unavailable' : `of ${formatBytes(snapshot.host.totalMemoryBytes, 0)}`}</small></div><div><span>Disk free</span><strong>{formatBytes(snapshot.host.freeDiskBytes, 0)}</strong></div></div></section>
        <section className={styles.railSection}><PanelTitle title={`${primary.name} load`} meta={primary.state} /><div className={styles.compactChart}>{primary.cpuPercent == null || primary.samples.length < 2 ? <p>{primary.state === 'Stopped' ? 'Start the server to collect performance data.' : 'Waiting for real samples.'}</p> : <><div className={styles.chartLegend}><strong>{primary.cpuPercent.toFixed(1)}%</strong><span>CPU · 15 min</span></div><Sparkline values={primary.samples.map(sample => sample.cpuPercent)} /></>}</div></section>
      </aside>
    </div>
  </div>;
}

export function ServersPage({ onOpenServer, onCreate }: { onOpenServer: (server: ServerSummary) => void; onCreate: () => void }) {
  const snapshot = useAppStore(state => state.snapshot)!;
  const command = useAppStore(state => state.command);
  const [search, setSearch] = useState('');
  const servers = useMemo(() => snapshot.servers.filter(server => `${server.name} ${server.ecosystem} ${server.minecraftVersion}`.toLowerCase().includes(search.toLowerCase())), [snapshot.servers, search]);
  const open = (server: ServerSummary) => onOpenServer(server);
  return <div className={styles.pageWrap}>
    <header className={styles.pageHeader}><div><h1>Servers</h1><p>Create, import, compare, and open your local servers.</p></div><div className={styles.actions}><Button icon={<Download size={15} />} onClick={() => void command('servers.import')}>Add existing</Button><Button variant="primary" icon={<Plus size={15} />} onClick={onCreate}>Create server</Button></div></header>
    <div className={styles.toolbar}><SearchInput value={search} onChange={event => setSearch(event.target.value)} placeholder="Search servers" aria-label="Search servers" /><span /><Button variant="subtle" icon={<RefreshCw size={14} />} onClick={() => void command('snapshot.refresh')}>Refresh</Button></div>
    {servers.length === 0 ? <div className={styles.panel}><EmptyState title={snapshot.servers.length ? 'No matching servers' : 'No servers yet'} detail={snapshot.servers.length ? 'Try a different server name, platform, or version.' : 'Create a managed server or add an existing folder.'} action={!snapshot.servers.length ? <Button variant="primary" onClick={onCreate}>Create server</Button> : undefined} /></div> : <div className={styles.cards}>{servers.map(server => { const choice = connectionChoice(server, snapshot.connectivity?.serverId === server.id ? snapshot.connectivity : null); return <article className={styles.serverCard} key={server.id}>
      <div className={styles.serverCardTop}><div className={styles.identity}><div className={styles.serverIcon}>{server.iconUrl ? <img src={server.iconUrl} alt="" aria-hidden="true" /> : <ServerIcon size={18} />}</div><div className={styles.identityText}><strong>{server.name}</strong><small>{server.ecosystem} · Minecraft {server.minecraftVersion}</small></div></div><StatusBadge tone={stateTone(server.state)}>{server.state}</StatusBadge></div>
      <div className={styles.serverCardMeta}><div><label>Players</label><span>{playerText(server)}</span></div><div><label>Memory</label><span>{formatBytes(server.memoryBytes)}</span></div><div><label>{choice.audience === 'internet' ? 'Internet address' : choice.audience === 'home' ? 'Same home network' : 'This computer'}</label><span>{choice.address ?? 'Not available yet'}</span>{choice.audience === 'internet' && <small>{choice.badge}</small>}</div><div><label>Backup</label><span>{server.lastBackupAt ? new Date(server.lastBackupAt).toLocaleDateString() : 'Not recorded'}</span></div></div>
      <div className={styles.serverCardActions}>{choice.kind && choice.address && <Button variant="subtle" icon={<Clipboard size={14} />} onClick={event => { event.stopPropagation(); void command('connectivity.copyAddress', { serverId: server.id, kind: choice.kind }); }}>Copy {choice.audience === 'internet' ? 'Internet' : choice.audience === 'home' ? 'home' : 'local'} address</Button>}<Button variant="subtle" icon={<FolderOpen size={14} />} onClick={() => void command('servers.openFolder', { serverId: server.id })}>Folder</Button><Button variant="primary" onClick={() => open(server)}>Manage</Button></div>
    </article>; })}</div>}
  </div>;
}

export function ActivityPage() {
  const snapshot = useAppStore(state => state.snapshot)!;
  return <div className={styles.pageWrap}><header className={styles.pageHeader}><div><h1>Activity</h1><p>Confirmed local operations from ChunkPilot.</p></div></header><section className={styles.panel}><PanelTitle title="Operation history" meta={`${snapshot.activity.length} recorded`} />{snapshot.activity.length ? <div className={styles.list}>{snapshot.activity.map(item => <div className={styles.row} key={item.id}><div className={styles.identityText}><strong>{item.action}</strong><small>{new Date(item.timestamp).toLocaleString()}</small></div><span>{item.serverName || 'ChunkPilot'}</span><StatusBadge tone={item.error ? 'danger' : 'success'}>{item.result}</StatusBadge><span>{(item.durationMs / 1000).toFixed(1)} s</span><span /></div>)}</div> : <EmptyState title="No activity recorded" detail="Confirmed operations appear here after they finish." />}</section></div>;
}

export function AutomationPage() {
  const snapshot = useAppStore(state => state.snapshot)!; const command = useAppStore(state => state.command);
  const server = snapshot.servers.find(item => item.id === snapshot.selectedServerId) ?? snapshot.servers[0];
  const [name, setName] = useState('Daily backup'); const [action, setAction] = useState('Backup'); const [kind, setKind] = useState('Interval'); const [intervalMinutes, setIntervalMinutes] = useState(1440); const [at, setAt] = useState('04:00'); const [pendingDelete, setPendingDelete] = useState<{ id: string; name: string } | null>(null);
  useEffect(() => { if (server && snapshot.selectedServerId !== server.id) void command('snapshot.selectServer', { serverId: server.id }); }, [server?.id, snapshot.selectedServerId]);
  const save = () => { if (!server || !name.trim()) return; void command('schedules.upsert', { serverId: server.id, name: name.trim(), action, kind, intervalMinutes, at, cron: '', command: '', restartCountdownSeconds: 60, backupBeforeRestart: action === 'Restart' }); };
  if (!server) return <div className={styles.pageWrap}><header className={styles.pageHeader}><div><h1>Automation</h1><p>Schedules for routine server work.</p></div></header><section className={styles.panel}><EmptyState title="No server selected" detail="Create or add a server before scheduling work." /></section></div>;
  return <div className={styles.pageWrap}><header className={styles.pageHeader}><div><h1>Automation</h1><p>Schedules keep running locally even while the interface is closed.</p></div><StatusBadge tone="info">{server.name}</StatusBadge></header><div className={styles.grid2}><section className={styles.panel}><PanelTitle title="Scheduled tasks" meta={`${snapshot.schedules.length} configured`} />{snapshot.schedules.length ? <div className={styles.list}>{snapshot.schedules.map(schedule => <div className={styles.row} key={schedule.id}><div className={styles.identity}><CalendarClock size={17} /><div className={styles.identityText}><strong>{schedule.name}</strong><small>{schedule.kind === 'Interval' ? `Every ${schedule.intervalMinutes} minutes` : `${schedule.kind} · ${schedule.at}`}</small></div></div><StatusBadge tone={schedule.enabled ? 'success' : 'neutral'}>{schedule.enabled ? 'Enabled' : 'Disabled'}</StatusBadge><span>{schedule.action}</span><span className={styles.muted}>{schedule.nextRunAt ? new Date(schedule.nextRunAt).toLocaleString() : 'Next run unavailable'}</span><Button variant="subtle" icon={<Trash2 size={14} />} onClick={() => setPendingDelete({ id: schedule.id, name: schedule.name })}>Remove</Button></div>)}</div> : <EmptyState title="No schedules" detail="Create a task for backups, restarts, saves, or another supported action." />}</section><section className={styles.panel}><PanelTitle title="Create schedule" meta="Runs locally" /><div className={styles.scheduleForm}><label>Task name<TextInput value={name} onChange={event => setName(event.target.value)} /></label><label>Action<select value={action} onChange={event => setAction(event.target.value)}>{['Backup', 'Restart', 'Save', 'Start', 'Stop', 'VerifyBackups', 'DeleteOldLogs'].map(value => <option key={value}>{value}</option>)}</select></label><label>Timing<select value={kind} onChange={event => setKind(event.target.value)}><option value="Interval">Repeating interval</option><option value="Daily">Daily</option></select></label>{kind === 'Interval' ? <label>Repeat every (minutes)<TextInput type="number" min={1} max={525600} value={intervalMinutes} onChange={event => setIntervalMinutes(Number(event.target.value))} /></label> : <label>Local time (24-hour)<TextInput value={at} onChange={event => setAt(event.target.value)} placeholder="04:00" /></label>}<Button variant="primary" disabled={!name.trim()} onClick={save}>Create schedule</Button></div></section></div><ConfirmDialog open={pendingDelete !== null} title="Remove scheduled task" detail={`Remove ${pendingDelete?.name ?? 'this task'}? Completed operation history is preserved.`} confirmLabel="Remove task" destructive onCancel={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) void command('schedules.delete', { serverId: server.id, scheduleId: pendingDelete.id }); setPendingDelete(null); }} /></div>;
}

export function DesignGalleryPage() {
  return <div className={styles.pageWrap}>
    <header className={styles.pageHeader}><div><h1>Forge Signal</h1><p>Development-only design system gallery for the locally rendered WebUI.</p></div><StatusBadge tone="info">Fixture mode</StatusBadge></header>
    <section className={styles.metricStrip} aria-label="Typography and status samples"><Metric label="Metric" value="18.4%" detail="Current CPU" /><Metric label="Memory" value="3.2 GB" detail="of 6 GB" /><Metric label="Players" value="4 / 12" detail="Authoritative" /><Metric label="Unknown" value="Unavailable" detail="Never presented as zero" /></section>
    <div className={`${styles.gridEven} ${styles.sectionGap}`}>
      <section className={styles.panel}><PanelTitle title="Controls" meta="Default, hover, focus, pending, disabled" /><div className={styles.actions}><Button variant="primary">Primary action</Button><Button>Secondary</Button><Button variant="subtle">Subtle</Button><Button variant="danger">Destructive</Button><Button disabled>Disabled</Button></div><div className={styles.toolbar}><SearchInput value="Copper" readOnly aria-label="Gallery search" /><StatusBadge tone="success">Running</StatusBadge><StatusBadge tone="warning">Updating</StatusBadge><StatusBadge tone="danger">Failed</StatusBadge></div></section>
      <section className={styles.panel}><PanelTitle title="Operational states" /><div className={styles.list}><div className={styles.row}><div className={styles.identityText}><strong>Confirmed success</strong><small>Authoritative local event</small></div><StatusBadge tone="success">Complete</StatusBadge><span /><span /><span /></div><div className={styles.row}><div className={styles.identityText}><strong>Starting server</strong><small>Nonblocking command acknowledgement</small></div><StatusBadge tone="info">Starting</StatusBadge><span /><span /><span /></div><div className={styles.row}><div className={styles.identityText}><strong>Unavailable value</strong><small>No invented fallback</small></div><StatusBadge tone="neutral">Unknown</StatusBadge><span /><span /><span /></div></div></section>
    </div>
    <section className={`${styles.panel} ${styles.sectionGap}`}><PanelTitle title="Dense table treatment" meta="Compact, aligned, scannable" /><div className={styles.list}>{['Copper Valley', 'Northern Works', 'Redstone Lab'].map((name, index) => <div className={styles.row} key={name}><div className={styles.identity}><div className={styles.serverIcon}><ServerIcon size={16} /></div><div className={styles.identityText}><strong>{name}</strong><small>{index === 1 ? 'Fabric · 1.21.1' : 'Vanilla · 1.21.8'}</small></div></div><StatusBadge tone={index === 2 ? 'danger' : index === 1 ? 'neutral' : 'success'}>{index === 2 ? 'Crashed' : index === 1 ? 'Stopped' : 'Running'}</StatusBadge><span className={styles.secondary}>{index === 1 ? 'Unavailable' : `${index + 2} players`}</span><span className={styles.secondary}>{index === 2 ? 'Port conflict' : 'Protected'}</span><Button variant="subtle">Open</Button></div>)}</div></section>
  </div>;
}
